services:
  - type: web
    name: bamn-api
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11.11
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r server/requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_PACKAGES_PATH
        value: /opt/render/project/src/.venv/lib/python3.11/site-packages
      - key: PYTHONPATH
        value: /opt/render/project/src/server 